export const ACTIVE_EVENT_NAMES = new Set([
  "login_succeeded",
  "trial_started",
  "program_enrolled",
  "course_enrolled",
  "course_started",
  "learning_message_sent",
  "exam_submitted",
  "course_completed",
  "agent_message_sent",
  "order_created",
  "payment_succeeded",
]);

export const LEARNING_EVENT_NAMES = new Set([
  "trial_started",
  "course_started",
  "learning_message_sent",
  "exam_submitted",
  "course_completed",
]);

export type MetricDefinition = {
  id: string;
  section: string;
  label: string;
  definition: string;
  source: string;
  window: string;
  status: "可靠" | "需积累" | "测试环境";
  caveat: string;
};

export const metricDefinitions: MetricDefinition[] = [
  {
    id: "registered-users",
    section: "账户",
    label: "注册学籍 / 正式账户",
    definition: "未软删除且不属于测试邮箱规则的用户账户数。",
    source: "users",
    window: "累计",
    status: "可靠",
    caveat: "邮箱验证尚未全面启用，因此注册不等于验证用户。",
  },
  {
    id: "new-users",
    section: "账户",
    label: "今日新增 / 7 日新增",
    definition: "按 Asia/Shanghai 日期统计建立学籍的正式账户。",
    source: "users.created_at",
    window: "自然日 / 最近 7×24 小时",
    status: "可靠",
    caveat: "排除 @example.com 与 +test@ 测试邮箱。",
  },
  {
    id: "active-users",
    section: "活跃",
    label: "7 日活跃用户",
    definition:
      "最近 7×24 小时内发生登录、旁听、选专业、选课、课堂学习、考试、Agent 对话、下单或支付任一有效行为的去重用户与匿名访客。",
    source: "analytics_events",
    window: "滚动 7 天",
    status: "需积累",
    caveat: "不把单纯页面浏览和注册本身算作活跃；埋点启用前的行为无法回溯。",
  },
  {
    id: "learning-users",
    section: "活跃",
    label: "7 日学习用户",
    definition:
      "最近 7×24 小时内发生旁听开始、课程开始、课堂发言、考试或课程完成行为的去重用户与匿名访客。",
    source: "analytics_events",
    window: "滚动 7 天",
    status: "需积累",
    caveat: "Agent 总对话不自动视为课程学习。",
  },
  {
    id: "completed-courses",
    section: "学习",
    label: "完成课程",
    definition: "通过期末考试的“用户 × 课程”唯一组合数。",
    source: "exam_attempts.passed",
    window: "累计 / 指定时间窗",
    status: "可靠",
    caveat: "同一课程多次通过只计算一次，避免重修重复计数。",
  },
  {
    id: "credits-earned",
    section: "学习",
    label: "获得学分",
    definition: "每个用户每门课程首次通过后获得学分的合计。",
    source: "exam_attempts.credits_earned",
    window: "累计",
    status: "可靠",
    caveat: "同一用户同一课程重考通过不会重复累计学分。",
  },
  {
    id: "model-cost",
    section: "成本",
    label: "模型成本",
    definition: "模型调用结束后按实际 token usage 结算的人民币分值合计。",
    source: "llm_call_logs.actual_fen",
    window: "自然日 / 累计",
    status: "可靠",
    caveat: "只代表模型 API 变动成本，不含服务器、人力和支付通道成本。",
  },
  {
    id: "visitors",
    section: "流量",
    label: "访问用户",
    definition: "发生 page_view 的用户或匿名访客标识去重数。",
    source: "analytics_events.page_view",
    window: "滚动 7 / 30 / 90 天",
    status: "需积累",
    caveat: "同一人更换浏览器或清除 Cookie 后可能被视为新访客。",
  },
  {
    id: "page-views",
    section: "流量",
    label: "页面浏览次数",
    definition: "page_view 事件次数，不去重。",
    source: "analytics_events.page_view",
    window: "最近 30 天",
    status: "需积累",
    caveat: "用于页面热度，不应解读为人数。",
  },
  {
    id: "conversion-funnel",
    section: "增长",
    label: "30 日核心转化",
    definition:
      "从近 30 天访问者开始，逐层取同一批身份中完成注册、进入学习、通过课程和完成选课的人数交集。",
    source: "analytics_events + users + exam_attempts + orders",
    window: "滚动 30 天",
    status: "需积累",
    caveat: "各层保持单调递减；埋点启用前进入漏斗的用户不会被补记。",
  },
  {
    id: "retention",
    section: "增长",
    label: "D1 / D7 / D30 学习留存",
    definition:
      "注册周 cohort 在注册后第 1–2 天、第 7–13 天、第 30–36 天再次发生有效行为的用户比例。",
    source: "users.created_at + analytics_events",
    window: "最近 8 个注册周",
    status: "需积累",
    caveat: "未成熟 cohort 显示“观察中”，不按 0% 处理。",
  },
  {
    id: "acquisition-source",
    section: "增长",
    label: "第一触点来源",
    definition:
      "每个身份最早一次可识别来源；优先使用追踪链接来源，其次为首个外部 referrer，最后归为直接访问。",
    source: "analytics_events.acquisition_source / referrer_host",
    window: "最近 120 天",
    status: "需积累",
    caveat: "一个用户只归入一个来源，避免跨来源重复计算。",
  },
  {
    id: "program-enrollment",
    section: "教务",
    label: "专业报名",
    definition: "处于有效状态的“用户 × 专业”唯一报名记录。",
    source: "user_programs",
    window: "累计",
    status: "可靠",
    caveat: "学院汇总按学生去重；专业明细按各专业分别去重。",
  },
  {
    id: "course-plan",
    section: "教务",
    label: "加入课程计划",
    definition: "课程出现在用户学习计划中的唯一用户数。",
    source: "user_course_plans",
    window: "累计",
    status: "可靠",
    caveat: "加入计划不等于已经开始学习。",
  },
  {
    id: "course-start",
    section: "教务",
    label: "开始课程",
    definition: "创建该课程学习会话的去重用户数。",
    source: "learning_sessions",
    window: "最近 180 天",
    status: "可靠",
    caveat: "只表示进入课程，不代表完成对话或考试。",
  },
  {
    id: "exam-average",
    section: "教务",
    label: "考试平均分",
    definition: "课程全部有效考试尝试的算术平均分，包含未通过和重考。",
    source: "exam_attempts.score",
    window: "最近 180 天",
    status: "可靠",
    caveat: "用于观察考试难度，不等于学生最终成绩平均值。",
  },
  {
    id: "geo",
    section: "地域",
    label: "国家 / 省份 / 城市",
    definition: "Cloudflare 网络边缘提供的访问城市级推断后按身份聚合。",
    source: "analytics_events.country / region / city",
    window: "最近 90 天",
    status: "需积累",
    caveat: "不保存明文 IP；VPN、代理和运营商出口可能造成城市误差。",
  },
  {
    id: "device",
    section: "地域",
    label: "访问设备",
    definition: "仅基于 page_view 的 User-Agent 粗分桌面、手机和平板后按身份去重。",
    source: "analytics_events.device_category",
    window: "最近 90 天",
    status: "需积累",
    caveat: "不生成设备指纹，未知或伪装 UA 可能分类不准。",
  },
  {
    id: "tracking-link",
    section: "渠道",
    label: "渠道访问 / 注册 / 学习",
    definition: "带 tracking_link_id 的访问者及其后续注册、学习行为去重数。",
    source: "tracking_links + analytics_events",
    window: "链接创建至今，归因 Cookie 90 天",
    status: "需积累",
    caveat: "采用第一方链接归因，不追踪站外行为。",
  },
  {
    id: "production-revenue",
    section: "财务",
    label: "生产净收入",
    definition: "生产支付模式中当前状态为 paid 的订单金额合计。",
    source: "orders.amount_fen, payment_mode=production",
    window: "累计 / 自然月",
    status: "可靠",
    caveat: "refunded 订单从净收入中剔除；尚未接入真实支付时应为 ¥0。",
  },
  {
    id: "test-volume",
    section: "财务",
    label: "测试交易额",
    definition: "测试支付模式中状态为 paid 的订单金额合计。",
    source: "orders.amount_fen, payment_mode=test",
    window: "累计 / 自然月",
    status: "测试环境",
    caveat: "不是真实收入，不进入生产 LTV、ARPU 或毛利。",
  },
  {
    id: "payers",
    section: "财务",
    label: "生产付费用户",
    definition: "至少拥有一笔生产模式 paid 订单的正式用户去重数。",
    source: "orders.user_id",
    window: "累计",
    status: "可靠",
    caveat: "测试支付用户单独展示，不混入正式付费率。",
  },
  {
    id: "arpu",
    section: "财务",
    label: "累计 ARPU",
    definition: "生产净收入 ÷ 全部正式注册用户。",
    source: "orders + users",
    window: "累计",
    status: "可靠",
    caveat: "早期样本很小时波动较大。",
  },
  {
    id: "arppu",
    section: "财务",
    label: "累计 ARPPU",
    definition: "生产净收入 ÷ 生产付费用户数。",
    source: "orders + users",
    window: "累计",
    status: "可靠",
    caveat: "没有生产付费用户时显示 ¥0，而不是推测值。",
  },
  {
    id: "ltv",
    section: "财务",
    label: "观测 LTV",
    definition:
      "按注册 cohort 计算截至当前累计生产净收入 ÷ cohort 注册人数；不是未来预测。",
    source: "users.created_at + production orders",
    window: "注册 cohort 生命周期至今",
    status: "可靠",
    caveat: "没有真实支付前只展示测试模拟 LTV，并明确标注。",
  },
  {
    id: "repeat-payer",
    section: "财务",
    label: "复购率",
    definition: "拥有至少两笔生产 paid 订单的用户 ÷ 生产付费用户。",
    source: "orders",
    window: "累计",
    status: "可靠",
    caveat: "退款订单不计入购买次数。",
  },
  {
    id: "wallet-topup",
    section: "财务",
    label: "测试储值",
    definition: "测试环境的学籍卡储值流水。",
    source: "wallet_transactions.type=test_topup",
    window: "累计",
    status: "测试环境",
    caveat: "储值既不是课程收入，也不激活会员等级，因此不进入 LTV。",
  },
];
